# Generated by Django 2.2.dev20180621213648 on 2018-10-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contrasenia',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
