# Generated by Django 2.1.2 on 2018-10-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='Imagenes/')),
                ('nombre_mascota', models.CharField(max_length=20)),
                ('raza_predominante', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
    ]
