# Generated by Django 2.1.2 on 2018-10-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_mascotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='fotografia',
            field=models.ImageField(upload_to='images'),
        ),
    ]
